name: Deploy to DigitalOcean
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Debug Information
        run: |
          echo "HOST: ${{ secrets.HOST }}"
          echo "USER: ${{ secrets.USERNAME }}"
      - name: Deploy to DigitalOcean
        env:
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USERNAME }}
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > deploy_key
          chmod 600 deploy_key
          echo "Attempting to connect to $USER@$HOST"
          ssh -v -i deploy_key -o StrictHostKeyChecking=no $USER@$HOST '
            echo "Connected successfully"
            cd /path/to/your/app &&
            git pull origin main &&
            npm install &&
            pm2 restart your-app-name
          '
