name: Deploy to DigitalOcean
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to DigitalOcean
        env:
          HOST_IP: ${{ secrets.HOST }}
          USER_NAME: ${{ secrets.USERNAME }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          echo "$SSH_PRIVATE_KEY" > deploy_key
          chmod 600 deploy_key
          echo "Attempting to connect to $USER_NAME@$HOST_IP"
          ssh -v -i deploy_key -o StrictHostKeyChecking=no $USER_NAME@$HOST_IP '
            echo "Connected successfully"
            hostname
            whoami
            pwd
          '
